/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import logica.Contador;

/**
 *
 * @author Estudiantes
 */
public class guiContador extends javax.swing.JFrame {
    private Contador contador = new Contador();
    /**
     * Creates new form NewJFrame
     */
    public guiContador() {
        initComponents();
        LBLvalor.setText(String.valueOf(contador.getValor()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        LBLetiquetaValor = new javax.swing.JLabel();
        LBLtitulo = new javax.swing.JLabel();
        LBLvalor = new javax.swing.JLabel();
        BTNcontar = new javax.swing.JButton();
        BTNdescontar = new javax.swing.JButton();
        BTNborrar = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLetiquetaValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LBLetiquetaValor.setText("Valor:");

        LBLtitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LBLtitulo.setText("Contador POO G87");

        LBLvalor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LBLvalor.setText("0");

        BTNcontar.setBackground(new java.awt.Color(255, 255, 0));
        BTNcontar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNcontar.setText("Contar");
        BTNcontar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcontarActionPerformed(evt);
            }
        });

        BTNdescontar.setBackground(new java.awt.Color(0, 255, 204));
        BTNdescontar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNdescontar.setText("Descontar");
        BTNdescontar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdescontarActionPerformed(evt);
            }
        });

        BTNborrar.setBackground(new java.awt.Color(204, 0, 0));
        BTNborrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNborrar.setText("Borrar");
        BTNborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(LBLtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNcontar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNdescontar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNborrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBLetiquetaValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                                .addComponent(LBLvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LBLtitulo)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLetiquetaValor)
                    .addComponent(LBLvalor))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNcontar)
                    .addComponent(BTNdescontar)
                    .addComponent(BTNborrar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNborrarActionPerformed
        contador.borrar();
        LBLvalor.setText(String.valueOf(contador.getValor()));
    }//GEN-LAST:event_BTNborrarActionPerformed

    private void BTNcontarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcontarActionPerformed
        contador.avanzar();
        LBLvalor.setText(String.valueOf(contador.getValor()));
    }//GEN-LAST:event_BTNcontarActionPerformed

    private void BTNdescontarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdescontarActionPerformed
        contador.retroceder();
        LBLvalor.setText(String.valueOf(contador.getValor()));
    }//GEN-LAST:event_BTNdescontarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiContador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNborrar;
    private javax.swing.JButton BTNcontar;
    private javax.swing.JButton BTNdescontar;
    private javax.swing.JLabel LBLetiquetaValor;
    private javax.swing.JLabel LBLtitulo;
    private javax.swing.JLabel LBLvalor;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
